<?php

use App\PlantillaDocumento;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddConvenioPrestacionesToPlantillaDocumentosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //plantilla para obtener header y footer
        $plantillaOrigen = PlantillaDocumento::find(1);
        //crear plantilla CONSTANCIA DE PAGO PARCIAL DE CONVENIO
        $plantillaDoc = PlantillaDocumento::create(
        [
            'nombre_plantilla'=> 'CONVENIO DE PRESTACIONES',
            'descripcion'=>'CONVENIO DE PRESTACIONES',
            'plantilla_header'=>$plantillaOrigen->plantilla_header,
            'plantilla_body'=>'<p style="line-height: 8pt;">&nbsp;</p>
            <p style="line-height: 8pt; text-align: right;">&nbsp;</p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong></strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CENTRO FEDERAL DE CONCILIACI&Oacute;N<br /><br />Y REGISTRO LABORAL<br /><br />OFICINA ESTATAL DE <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>&nbsp; <br /><br />N&Uacute;MERO DE IDENTIFICACI&Oacute;N &Uacute;NICO <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong>&nbsp; <br /><br /><br />LIGA &Uacute;NICA: https://conciliacion.centrolaboral.gob.mx/canal/<strong class="mceNonEditable" data-nombre="solicitud_canal">[SOLICITUD_CANAL]</strong>&nbsp; <br />&nbsp;<br /><br /></strong></span></p>
            <p style="line-height: 8pt; text-align: right;">&nbsp;</p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong> <strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong></strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><br />&nbsp;</strong></span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CENTRO FEDERAL DE CONCILIACI&Oacute;N </strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>Y REGISTRO LABORAL</strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>OFICINA ESTATAL DE <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>&nbsp; &nbsp;</strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>N&Uacute;MERO DE IDENTIFICACI&Oacute;N &Uacute;NICO <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong></strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><br /><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong>&nbsp;</p>
            <p style="line-height: 8pt; text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CONVENIO DE CONCILIACi&Oacute;N <strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong>V&Iacute;A REMOTA <strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong> <strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong>&nbsp; </strong></span></p>
            <p style="line-height: 8pt; text-align: right;">&nbsp;</p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">Con fundamento en los art&iacute;culos 123, apartado A, fracci&oacute;n XXVII, inciso h) p&aacute;rrafo segundo, de la Constituci&oacute;n Pol&iacute;tica de los Estados Unidos Mexicanos; art&iacute;culo 33 y 684-E de la Ley Federal del Trabajo, se celebra el presente convenio por una parte <strong class="mceNonEditable" data-nombre="solicitante_nombre_completo">[SOLICITANTE_NOMBRE_COMPLETO]</strong> </span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">qui&eacute;n en lo subsecuente se denominar&aacute; la parte &ldquo;<strong>TRABAJADORA</strong>&rdquo; y, por otro <strong class="mceNonEditable" data-nombre="resolucion_citados_convenio">[RESOLUCION_CITADOS_CONVENIO]</strong> a qui&eacute;n en lo subsecuente se le denominar&aacute; la parte &ldquo;<strong>EMPLEADORA</strong>&rdquo;, a quienes en lo sucesivo de forma conjunta se les denominar&aacute; las <strong>&ldquo;PARTES&rdquo;</strong>, quienes se someten y obligan en t&eacute;rminos de las siguientes declaraciones y cl&aacute;usulas:</span></p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>D E C L A R A C I O N E S:</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>PRIMERA</strong>. La parte <strong>TRABAJADORA </strong>se identifica con <strong class="mceNonEditable" data-nombre="solicitante_identificacion_documento">[SOLICITANTE_IDENTIFICACION_DOCUMENTO]</strong> expedida a su favor por <strong class="mceNonEditable" data-nombre="solicitante_identificacion_expedida_por">[SOLICITANTE_IDENTIFICACION_EXPEDIDA_POR]</strong>&nbsp; y declara ser una persona mayor de edad, por lo que tiene plenas capacidades de goce y ejercicio para convenir o transigir.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>SEGUNDA. </strong></span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><span style="font-weight: bolder;"><span style="font-weight: 400;">Declara <strong class="mceNonEditable" data-nombre="resolucion_segunda_declaracion_convenio">[RESOLUCION_SEGUNDA_DECLARACION_CONVENIO]</strong></span></span></span></p>
            <p><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>TERCERA</strong>. Declara la parte <strong>TRABAJADORA</strong>:&nbsp;</span></p>
            <p style="padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">a)Que fue contratada por la parte <strong>EMPLEADORA</strong> desde el <strong><strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_fecha_ingreso">[SOLICITANTE_DATOS_LABORALES_FECHA_INGRESO]</strong></strong>, para prestar sus servicios como <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_puesto">[SOLICITANTE_DATOS_LABORALES_PUESTO]</strong>, puesto en el que se desempe&ntilde;&oacute; hasta el d&iacute;a <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_fecha_salida">[SOLICITANTE_DATOS_LABORALES_FECHA_SALIDA]</strong>.</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">b) Que por el desempe&ntilde;o de sus labores contaba con las siguientes prestaciones:</span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Salario mensual:<strong> $<strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_salario_mensual">[SOLICITANTE_DATOS_LABORALES_SALARIO_MENSUAL]</strong> </strong>(<strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_salario_mensual_letra">[SOLICITANTE_DATOS_LABORALES_SALARIO_MENSUAL_LETRA]</strong> moneda nacional).&nbsp;</span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- D&iacute;as de descanso: <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_dias_descanso">[SOLICITANTE_DATOS_LABORALES_DIAS_DESCANSO]</strong></span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Vacaciones: <strong><strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_dias_vacaciones">[SOLICITANTE_DATOS_LABORALES_DIAS_VACACIONES]</strong></strong>&nbsp;d&iacute;as al a&ntilde;o.</span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Aguinaldo:<strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_dias_aguinaldo">[SOLICITANTE_DATOS_LABORALES_DIAS_AGUINALDO]</strong> d&iacute;as al a&ntilde;o.</span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Otras prestaciones (bonos, vales de despensa, seguros de gastos m&eacute;dicos mayores etc): <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_prestaciones_adicionales">[SOLICITANTE_DATOS_LABORALES_PRESTACIONES_ADICIONALES]</strong>.</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">c) Que desempe&ntilde;ana sus actividades laborales en las siguientes condiciones:&nbsp;</span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Horario: <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_horario_laboral">[SOLICITANTE_DATOS_LABORALES_HORARIO_LABORAL]</strong></span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Horario de comida: de <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_horario_comida">[SOLICITANTE_DATOS_LABORALES_HORARIO_COMIDA]</strong> <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_comida_dentro">[SOLICITANTE_DATOS_LABORALES_COMIDA_DENTRO]</strong>&nbsp; de las instalaciones.</span></p>
            <p style="text-align: justify; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Domicilio donde prestaba sus servicios: <strong class="mceNonEditable" data-nombre="solicitado_domicilios_completo">[SOLICITADO_DOMICILIOS_COMPLETO]</strong><strong>.</strong></span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">d) Que el d&iacute;a <strong><strong class="mceNonEditable" data-nombre="solicitud_fecha_ratificacion">[SOLICITUD_FECHA_RATIFICACION]</strong></strong> present&oacute; solicitud para iniciar el procedimiento de conciliaci&oacute;n prejudicial ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal de <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong>, por motivo de&nbsp; <strong class="mceNonEditable" data-nombre="solicitud_objeto_solicitudes">[SOLICITUD_OBJETO_SOLICITUDES]</strong>.</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">e) Que el Centro Federal, fij&oacute; la audiencia de conciliaci&oacute;n para el d&iacute;a&nbsp; <strong class="mceNonEditable" data-nombre="audiencia_fecha_audiencia">[AUDIENCIA_FECHA_AUDIENCIA]</strong>.</span></p>
            <p style="text-align: justify;"><br /><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CUARTA</strong>. Declara la parte <strong>EMPLEADORA</strong>:</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">a)Que la parte <strong>TRABAJADORA</strong>, fue contratada para laborar como <strong class="mceNonEditable" data-nombre="solicitante_datos_laborales_puesto">[SOLICITANTE_DATOS_LABORALES_PUESTO]</strong> en el domicilio ubicado en <strong><strong class="mceNonEditable" data-nombre="solicitado_domicilios_completo">[SOLICITADO_DOMICILIOS_COMPLETO]</strong>.</strong></span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">b)Que con motivo del citatorio de fecha <strong class="mceNonEditable" data-nombre="solicitado_fecha_notificacion">[SOLICITADO_FECHA_NOTIFICACION]</strong> emitido por el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>,&nbsp;la parte <strong>EMPLEADORA</strong> comparece para desahogar la etapa de conciliaci&oacute;n prejudicial conforme al Art&iacute;culo 684-E de la Ley Federal del Trabajo..</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>QUINTA</strong>. Declaran las <strong>PARTES</strong>:</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong></span></p>
            <p style="padding-left: 40px; text-align: justify;">a)Conocer el contenido del Acuerdo por el que se establece la suspensi&oacute;n de plazos y t&eacute;rminos en el Centro Federal de Conciliaci&oacute;n y Registro Laboral publicado el 21 de diciembre de 2020 en el Diario Oficial de la Federaci&oacute;n, por virtud del cual el Centro Federal de Conciliaci&oacute;n y Registro Laboral est&aacute; facultado para celebrar audiencias &nbsp;de conciliaci&oacute;n v&iacute;a remota y, como consecuencia, las PARTES se obligan al cumplimiento de lo pactado durante la celebraci&oacute;n de la audiencia en l&iacute;nea, mismo que se detalla en el cuerpo del presente convenio.&nbsp;</p>
            <p style="padding-left: 40px; text-align: justify;">b)&nbsp;<span style="font-size: 12pt; letter-spacing: 0px;">Que el d&iacute;a</span><span style="font-size: 12pt; letter-spacing: 0px;"> <strong class="mceNonEditable" data-nombre="audiencia_fecha_resolucion">[AUDIENCIA_FECHA_RESOLUCION]</strong></span><span style="text-align: justify;">, se celebr&oacute; la audiencia de conciliaci&oacute;n v&iacute;a remota a trav&eacute;s de la liga &uacute;nica https://conciliacion.centrolaboral.gob.mx/canal/</span><span class="mceNonEditable" style="font-weight: bolder; text-align: justify;" data-nombre="solicitud_canal">[SOLICITUD_CANAL]</span> ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>,&nbsp;bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong>.</p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">c) Que el presente convenio se celebra con la finalidad de dar por terminado el procedimiento de conciliaci&oacute;n prejudicial, seguido ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>, bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong>&nbsp; al tenor de las siguientes:&nbsp;</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><br /><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong></span></p>
            <p style="padding-left: 40px; text-align: justify;"><span style="font-size: 12pt;">a)Que el d&iacute;a <strong class="mceNonEditable" data-nombre="audiencia_fecha_resolucion">[AUDIENCIA_FECHA_RESOLUCION]</strong></span><span style="font-size: 12pt;">, se celebr&oacute; la audiencia de conciliaci&oacute;n ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal </span><strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong><span style="font-size: 12pt;">, bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico </span><strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong><span style="font-size: 12pt;"> .</span></p>
            <p style="padding-left: 40px; text-align: justify;"><span style="font-size: 12pt;">b) Que el presente convenio se celebra con la finalidad de dar por terminado el procedimiento de conciliaci&oacute;n prejudicial, seguido ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal </span><strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong><span style="font-size: 12pt;">, bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico </span><strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong><span style="font-size: 12pt;">&nbsp; &nbsp;al tenor de las siguientes:&nbsp;</span></p>
            <p style="padding-left: 40px;"><span style="font-size: 14pt; letter-spacing: 0px;">.</span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong></span></p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>C L &Aacute; U S U L A S:</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>PRIMERA</strong>. Las <strong>PARTES</strong>&nbsp;han determinado que por as&iacute; convenir a sus intereses dan por concluida la relaci&oacute;n laboral por mutuo acuerdo, conforme a lo estipulado por el art&iacute;culo 53, fracci&oacute;n I, de la Ley Federal del Trabajo.&nbsp;</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>SEGUNDA</strong>. La parte <strong>TRABAJADORA</strong> manifiesta bajo protesta de decir verdad, que el v&iacute;nculo laboral lo mantuvo exclusivamente con la parte <strong>EMPLEADORA</strong>. Por lo anterior, expresa que no existi&oacute; relaci&oacute;n laboral alguna con otras personas, incluido el personal que fung&iacute;a como superior jer&aacute;rquico en el centro de trabajo donde la parte <strong>TRABAJADORA</strong> desempe&ntilde;aba sus labores.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>TERCERA</strong>. La parte <strong>EMPLEADORA</strong> otorga en favor de la parte <strong>TRABAJADORA</strong> el pago acordado conforme a las disposiciones de la Ley Federal del Trabajo. La parte <strong>TRABAJADORA</strong> manifiesta su entera conformidad y la aceptaci&oacute;n de &eacute;ste, as&iacute; como la forma en que se obtuvieron los conceptos que se describen en la cl&aacute;usula <strong>QUINTA</strong>.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">&nbsp;<strong>CUARTA</strong>. La parte <strong>TRABAJADORA</strong> manifiesta que durante el tiempo que labor&oacute; para la parte <strong>EMPLEADORA</strong>, se cubri&oacute; en tiempo y forma el pago su salario; cada una de las prestaciones ordinarias y extraordinarias y en especie que conforme a derecho le corresponden, as&iacute; mismo como cualquier riesgo o accidente de trabajo que haya sufrido. Por lo anterior, la parte <strong>EMPLEADORA</strong> no adeuda pago de concepto alguno.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>QUINTA</strong>. La parte <strong>TRABAJADORA</strong> recibir&aacute; por parte de la parte <strong>EMPLEADORA</strong> la cantidad de <strong>$<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones">[RESOLUCION_TOTAL_PERCEPCIONES]</strong>&nbsp; </strong>(<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones_letra">[RESOLUCION_TOTAL_PERCEPCIONES_LETRA]</strong> moneda nacional), conforme a los siguientes conceptos:</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="resolucion_propuesta_configurada">[RESOLUCION_PROPUESTA_CONFIGURADA]</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="resolucion_justificacion_propuesta">[RESOLUCION_JUSTIFICACION_PROPUESTA]</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[SI_RESOLUCION_PAGO_DIFERIDO]</strong><strong>SEXTA.</strong>La parte <strong>EMPLEADORA</strong> manifiesta que pagar&aacute; en <strong class="mceNonEditable" data-nombre="resolucion_total_diferidos">[RESOLUCION_TOTAL_DIFERIDOS]</strong> exhibiciones, hasta culminar la cantidad de $<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones">[RESOLUCION_TOTAL_PERCEPCIONES]</strong> (<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones_letra">[RESOLUCION_TOTAL_PERCEPCIONES_LETRA]</strong> moneda nacional), tal como se muestra:</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="resolucion_pagos_diferidos">[RESOLUCION_PAGOS_DIFERIDOS]</strong>&nbsp; </span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">En caso de que la parte <strong>EMPLEADORA</strong> no cubra el pago de la cantidad estipulada y dentro del plazo determinado en esta cl&aacute;usula, deber&aacute; pagar a la parte <strong>TRABAJADORA</strong> el equivalente a un d&iacute;a de salario diario, el cual se fijar&aacute; en raz&oacute;n del salario que percib&iacute;a dicha parte antes de finalizar la relaci&oacute;n de trabajo. Esa cantidad se sumar&aacute; a la previamente pactada, por cada d&iacute;a que transcurra, sin que se d&eacute; cabal cumplimiento al convenio, con fundamento en el art&iacute;culo 684-E, fracci&oacute;n XIV, &uacute;ltimo p&aacute;rrafo, de la Ley Federal del Trabajo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[SI_RESOLUCION_PAGO_NO_DIFERIDO]</strong><span style="font-weight: bolder;">SEXTA.</span> La parte <span style="font-weight: bolder;">EMPLEADORA</span> manifiesta que en este acto en fecha <strong class="mceNonEditable" data-nombre="audiencia_fecha_resolucion">[AUDIENCIA_FECHA_RESOLUCION]</strong> le paga a la parte <span style="font-weight: bolder;">TRABAJADORA</span>&nbsp;<strong>en una sola exhibici&oacute;n</strong> la cantidad de $<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones">[RESOLUCION_TOTAL_PERCEPCIONES]</strong>&nbsp; (<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones_letra">[RESOLUCION_TOTAL_PERCEPCIONES_LETRA]</strong> moneda nacional), en el domicilio que ocupa el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal de <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong>&nbsp; con lo que se certifica el cumplimiento de su obligaci&oacute;n bajo el presente convenio, de conformidad con lo establecido en el art&iacute;culo 684-E, fracci&oacute;n XIV, de la Ley Federal del Trabajo.<br /><strong class="mceNonEditable" data-nombre="">[FIN_SI_RESOLUCION_PAGO]</strong>&nbsp; </span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>S&Eacute;PTIMA</strong>. Las <strong>PARTES</strong> solicitan se apruebe y sancione este convenio, toda vez que se elabor&oacute; conforme a las disposiciones aplicables de la Ley Federal del Trabajo como resultado del di&aacute;logo de la conciliaci&oacute;n entre la parte <strong>TRABAJADORA</strong> y la parte <strong>EMPLEADORA</strong>. Asimismo, manifiestan que se encuentran conformes con el presente acuerdo por no contener cl&aacute;usula contraria a la costumbre, a la moral, ni renuncia a los derechos de las <strong>PARTES</strong>.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>OCTAVA</strong>. Las<strong> PARTES</strong>&nbsp;manifiestan que es su voluntad ratificar el presente convenio en todas y cada una de sus partes y la aprobaci&oacute;n de su contenido, por lo que no se reservan acci&oacute;n legal o derecho alguno para ejercitar con posterioridad a la firma del presente convenio.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>NOVENA</strong>. Las<strong> PARTES</strong> solicitan ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral que les sean expedidas las copias autorizadas del convenio, y en caso de tener pagos diferidos, que en el momento en que se haya cumplido totalmente, se les expida acta en la que conste el cumplimiento de &eacute;ste, en t&eacute;rminos del art&iacute;culo 684-E, fracci&oacute;n XIV, primer p&aacute;rrafo, de la Ley Federal del Trabajo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>D&Eacute;CIMA.</strong> Las<strong> PARTES</strong> manifiestan que en la celebraci&oacute;n del presente convenio no existi&oacute; violencia, mala fe, dolo, lesi&oacute;n o cualquier otro tipo de vicio del consentimiento que pudiera nulificarlo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>D&Eacute;CIMA PRIMERA.</strong> En caso de que no se cumplan los t&eacute;rminos de lo convenido en el presente instrumento, las <strong>PARTES</strong>&nbsp;deber&aacute;n acudir a los Tribunales Laborales a efecto de que se realice el procedimiento de ejecuci&oacute;n que la Ley Federal del Trabajo contempla.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">Enteradas las <strong>PARTES</strong>&nbsp;del alcance legal del presente convenio que se eleva a cosa juzgada, conforme al art&iacute;culo 684-E fracci&oacute;n XIII, mismo que se firma en <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong> a los <strong><strong class="mceNonEditable" data-nombre="audiencia_fecha_resolucion">[AUDIENCIA_FECHA_RESOLUCION]</strong></strong>, ante la fe de <strong class="mceNonEditable" data-nombre="conciliador_nombre_completo">[CONCILIADOR_NOMBRE_COMPLETO]</strong><strong>,</strong>&nbsp;funcionario conciliador, quien lo sanciona en este mismo acto. <strong>Doy fe.</strong></span></p>
            <p style="text-align: justify;">&nbsp;</p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong><br /></strong></span></p>
            <p style="text-align: center;"><strong class="mceNonEditable" data-nombre="solicitud_firmas_partes_qr">[SOLICITUD_FIRMAS_PARTES_QR]</strong>&nbsp;</p>
            <p style="text-align: center;"><strong class="mceNonEditable" data-nombre="conciliador_qr_firma">[CONCILIADOR_QR_FIRMA]</strong>&nbsp;</p>
            <p style="text-align: center;">___________________________________________<br /><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="conciliador_nombre_completo">[CONCILIADOR_NOMBRE_COMPLETO]</strong>&nbsp; </strong>&nbsp;&nbsp;<strong>&nbsp;<br /></strong></span><strong><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">FUNCIONARIO CONCILIADOR</span></strong></p>
            <p style="text-align: justify;"><strong><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">Los c&oacute;digos QR asociadas a cada una de las partes no representan una forma de manifestaci&oacute;n de la voluntad, sin embargo, se convierten en firma electr&oacute;nica en caso de que la parte firmante utilice su firma electr&oacute;nica avanzada para manifestar su voluntad. Para que el solicitante y/o el citado se puedan utilizar los c&oacute;digos QR ser&aacute; necesario que todas las partes firmantes cuenten con la firma electr&oacute;nica avanzada de lo contrario deber&aacute;n acudir a la Oficina Estatal del CFCRL para firmar el documento de manera aut&oacute;grafa.</span></strong></p>
            <p><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong></p>
            <p>&nbsp;</p>
            <table style="border-collapse: collapse; width: 100%; border-style: dashed;" border="1">
            <tbody>
            <tr>
            <td style="width: 50%;">
            <p style="text-align: center;"><strong>_________________________ &nbsp; &nbsp; &nbsp;</strong></p>
            <p style="text-align: center;"><strong>LA PARTE TRABAJADORA&nbsp;</strong></p>
            </td>
            <td style="width: 50%;">
            <p style="text-align: center;"><strong>&nbsp;________________________</strong></p>
            <p style="text-align: center;"><strong>LA PARTE EMPLEADORA</strong></p>
            </td>
            </tr>
            </tbody>
            </table>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;"><span style="text-decoration: underline;">_______________________________________________</span><br />&nbsp;<strong> </strong><strong class="mceNonEditable" data-nombre="conciliador_nombre_completo">[CONCILIADOR_NOMBRE_COMPLETO]</strong><strong>&nbsp; &nbsp;<br /></strong><strong>FUNCIONARIO CONCILIADOR</strong></p>
            <p style="text-align: left;"><br /><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong><strong>&nbsp;</strong></p>
            <p>&nbsp;</p>
            ',
            'plantilla_footer' => $plantillaOrigen->plantilla_footer,
            'tipo_documento_id' => 3
            ]
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('plantilla_documentos', function (Blueprint $table) {
            //
        });
    }
}
