<?php

use App\PlantillaDocumento;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddConvenioReinstalacionPatronalToPlantillaDocumentosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //plantilla para obtener header y footer
        $plantillaOrigen = PlantillaDocumento::find(1);
        //crear plantilla CONSTANCIA DE PAGO PARCIAL DE CONVENIO
        $plantillaDoc = PlantillaDocumento::create(
        [
            'nombre_plantilla'=> 'CONVENIO DE REINSTALACIÓN PATRONAL',
            'descripcion'=>'CONVENIO DE REINSTALACIÓN PATRONAL',
            'plantilla_header'=>$plantillaOrigen->plantilla_header,
            'plantilla_body'=>'<p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CENTRO FEDERAL DE CONCILIACI&Oacute;N </strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>Y REGISTRO LABORAL.</strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>OFICINA ESTATAL DE <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>&nbsp; &nbsp;</strong></span></p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>N&Uacute;MERO DE IDENTIFICACI&Oacute;N &Uacute;NICO <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong>&nbsp;</strong></span></p>
            <p style="line-height: 8pt; text-align: right;">&nbsp;</p>
            <p style="line-height: 8pt; text-align: right;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong>LIGA &Uacute;NICA: https://conciliacion.centrolaboral.gob.mx/canal/<strong class="mceNonEditable" data-nombre="solicitud_canal">[SOLICITUD_CANAL]</strong>&nbsp; </strong></span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>&nbsp;<br /><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong><br /><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong>&nbsp; </strong></span></p>
            <p style="line-height: 8pt; text-align: center;">&nbsp;</p>
            <p style="line-height: 8pt; text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CONVENIO DE CONCILIACI&Oacute;N<strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong> V&Iacute;A REMOTA<strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong>&nbsp; </strong></span></p>
            <p style="line-height: 8pt;">&nbsp;</p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">Con fundamento en los art&iacute;culos 123, apartado A, fracci&oacute;n XXVII, inciso h) p&aacute;rrafo segundo, de la Constituci&oacute;n Pol&iacute;tica de los Estados Unidos Mexicanos; 33, 48 y 684-E de la Ley Federal del Trabajo, se celebra el presente convenio por una parte <strong class="mceNonEditable" data-nombre="solicitante_nombre_completo">[SOLICITANTE_NOMBRE_COMPLETO]</strong> </span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">qui&eacute;n en lo subsecuente se denominar&aacute; la parte &ldquo;<strong>EMPLEADORA</strong>&rdquo; y, por otro <strong class="mceNonEditable" data-nombre="solicitado_nombre_completo">[SOLICITADO_NOMBRE_COMPLETO]</strong> a qui&eacute;n en lo subsecuente se le denominar&aacute; la parte &ldquo;<strong>TRABAJADORA</strong>&rdquo;, a quienes en lo sucesivo de forma conjunta se les denominar&aacute; las<strong>&nbsp;"PARTES&rdquo;</strong>, quienes se someten y obligan en t&eacute;rminos de las siguientes declaraciones y cl&aacute;usulas:</span></p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>D E C L A R A C I O N E S:</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>PRIMERA</strong>. La parte <strong>TRABAJADORA </strong>se identifica con <strong class="mceNonEditable" data-nombre="solicitado_identificacion_documento">[SOLICITADO_IDENTIFICACION_DOCUMENTO]</strong> expedida a su favor por <strong class="mceNonEditable" data-nombre="solicitado_identificacion_expedida_por">[SOLICITADO_IDENTIFICACION_EXPEDIDA_POR]</strong> y, declara ser una persona mayor de edad, por lo que tiene plenas capacidades de goce y ejercicio para convenir o transigir.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>SEGUNDA. </strong></span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><span style="font-weight: bolder;"><span style="font-weight: 400;">Declara <strong class="mceNonEditable" data-nombre="">[SI_SOLICITANTE_TIPO_PERSONA_FISICA]</strong> <strong class="mceNonEditable" data-nombre="solicitante_nombre_completo">[SOLICITANTE_NOMBRE_COMPLETO]</strong> quien se identifica con <strong class="mceNonEditable" data-nombre="solicitante_identificacion_documento">[SOLICITANTE_IDENTIFICACION_DOCUMENTO]</strong> tener plenas capacidades de goce y ejercicio para convenir el presente instrumento <br /><strong class="mceNonEditable" data-nombre="">[SI_SOLICITANTE_TIPO_PERSONA_MORAL]</strong> <strong class="mceNonEditable" data-nombre="solicitante_representante_legal_nombre_completo">[SOLICITANTE_REPRESENTANTE_LEGAL_NOMBRE_COMPLETO]</strong> quien se identifica con <strong class="mceNonEditable" data-nombre="solicitante_representante_legal_identificacion_documento">[SOLICITANTE_REPRESENTANTE_LEGAL_IDENTIFICACION_DOCUMENTO]</strong>, que es apoderado legal de <strong class="mceNonEditable" data-nombre="solicitante_nombre_completo">[SOLICITANTE_NOMBRE_COMPLETO]</strong> y que cuenta con facultades suficientes para convenir a nombre de su representada en t&eacute;rminos de&nbsp; <strong class="mceNonEditable" data-nombre="solicitante_representante_legal_detalle_instrumento">[SOLICITANTE_REPRESENTANTE_LEGAL_DETALLE_INSTRUMENTO]</strong>, poder que a la fecha de este convenio no le ha sido revocado.<br /><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITANTE_TIPO_PERSONA]</strong>&nbsp; </span></span><strong><br /></strong></span></p>
            <p><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>TERCERA</strong>. Declara la parte <strong>TRABAJADORA</strong>:&nbsp;</span></p>
            <p style="padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">a)Que fue contratada por la parte <strong>EMPLEADORA</strong> desde el <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_fecha_ingreso">[SOLICITADO_DATOS_LABORALES_FECHA_INGRESO]</strong>, para prestar sus servicios como <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_puesto">[SOLICITADO_DATOS_LABORALES_PUESTO]</strong>, puesto en el que se desempe&ntilde;&oacute; hasta el d&iacute;a <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_fecha_salida">[SOLICITADO_DATOS_LABORALES_FECHA_SALIDA]</strong> que aleg&oacute; ser despedida por su empleador.</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">b) Que por el desempe&ntilde;o de sus labores contaba con las siguientes prestaciones:</span></p>
            <p style="text-align: justify; line-height: 8pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Salario mensual:<strong> $<strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_salario_mensual">[SOLICITADO_DATOS_LABORALES_SALARIO_MENSUAL]</strong> &nbsp;</strong>(<strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_salario_mensual_letra">[SOLICITADO_DATOS_LABORALES_SALARIO_MENSUAL_LETRA]</strong> pesos 00/100 moneda nacional).&nbsp;</span></p>
            <p style="text-align: justify; line-height: 8pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- D&iacute;as de descanso: <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_dias_descanso">[SOLICITADO_DATOS_LABORALES_DIAS_DESCANSO]</strong>.</span></p>
            <p style="text-align: justify; line-height: 8pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Vacaciones: <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_dias_vacaciones">[SOLICITADO_DATOS_LABORALES_DIAS_VACACIONES]</strong>&nbsp;d&iacute;as al a&ntilde;o.</span></p>
            <p style="text-align: justify; line-height: 8pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Aguinaldo:<strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_dias_aguinaldo">[SOLICITADO_DATOS_LABORALES_DIAS_AGUINALDO]</strong> d&iacute;as al a&ntilde;o.</span></p>
            <p style="text-align: justify; line-height: 11pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Otras prestaciones (bonos, vales de despensa, seguros de gastos m&eacute;dicos mayores etc): <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_prestaciones_adicionales">[SOLICITADO_DATOS_LABORALES_PRESTACIONES_ADICIONALES]</strong>.</span></p>
            <p style="text-align: justify; line-height: 11pt; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">c) Que desempe&ntilde;aba sus actividades laborales en las siguientes condiciones:&nbsp;</span></p>
            <p style="text-align: justify; line-height: 11pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Horario: <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_horario_laboral">[SOLICITADO_DATOS_LABORALES_HORARIO_LABORAL]</strong></span></p>
            <p style="text-align: justify; line-height: 11pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Horario de comida: de <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_horario_comida">[SOLICITADO_DATOS_LABORALES_HORARIO_COMIDA]</strong>&nbsp; <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_comida_dentro">[SOLICITADO_DATOS_LABORALES_COMIDA_DENTRO]</strong> de las instalaciones.</span></p>
            <p style="text-align: justify; line-height: 11pt; padding-left: 80px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">- Domicilio : ubicado en <strong class="mceNonEditable" data-nombre="solicitado_domicilios_completo">[SOLICITADO_DOMICILIOS_COMPLETO]</strong><strong>.</strong></span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">d) Que el d&iacute;a <strong><strong class="mceNonEditable" data-nombre="solicitud_fecha_ratificacion">[SOLICITUD_FECHA_RATIFICACION]</strong></strong> present&oacute; solicitud para iniciar el procedimiento de conciliaci&oacute;n prejudicial ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal de <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong>, por motivo de <strong class="mceNonEditable" data-nombre="solicitud_objeto_solicitudes">[SOLICITUD_OBJETO_SOLICITUDES]</strong>.</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">e) Que el Centro Federal, fij&oacute; la audiencia de conciliaci&oacute;n para el d&iacute;a <strong class="mceNonEditable" data-nombre="audiencia_fecha_audiencia">[AUDIENCIA_FECHA_AUDIENCIA]</strong>.</span></p>
            <p style="text-align: justify;"><br /><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CUARTA</strong>. Declara la parte <strong>EMPLEADORA</strong>:</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">a)Que la parte <strong>TRABAJADORA</strong>, fue contratada para laborar como <strong class="mceNonEditable" data-nombre="solicitado_datos_laborales_puesto">[SOLICITADO_DATOS_LABORALES_PUESTO]</strong> en el domicilio ubicado en <strong class="mceNonEditable" data-nombre="solicitado_domicilios_completo">[SOLICITADO_DOMICILIOS_COMPLETO]</strong><strong>.</strong></span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">b)Que con motivo del citatorio de fecha <strong class="mceNonEditable" data-nombre="solicitado_fecha_notificacion">[SOLICITADO_FECHA_NOTIFICACION]</strong>, emitido por el Centro Federal de Conciliacion y Registro Laboral, Oficina Estatal de <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong> la parte <strong>EMPLEADORA</strong>, comparece para desahogar la etapa se conciliaci&oacute;n prejudicial conforme a los articulos 684-E de la Ley Federal del Trabajo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>QUINTA</strong>. Declaran las <strong>PARTES</strong>:</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong><br /></span></p>
            <p style="text-align: justify; padding-left: 40px;">a)Conocer el contenido del Acuerdo por el que se establece la suspensi&oacute;n de plazos y t&eacute;rminos en el Centro Federal de Conciliaci&oacute;n y Registro Laboral publicado el 21 de diciembre de 2020 en el Diario Oficial de la Federaci&oacute;n, por virtud del cual el Centro Federal de Conciliaci&oacute;n y Registro Laboral est&aacute; facultado para celebrar audiencias &nbsp;de conciliaci&oacute;n en l&iacute;nea y, como consecuencia, las <strong>PARTES</strong> se obligan al cumplimiento de lo pactado durante la celebraci&oacute;n de la audiencia en l&iacute;nea, mismo que se detalla en el cuerpo del presente convenio.&nbsp;</p>
            <p style="text-align: justify; padding-left: 40px;">b) Que el d&iacute;a <strong class="mceNonEditable" data-nombre="fecha_actual">[FECHA_ACTUAL]</strong> se celebr&oacute; la audiencia de conciliaci&oacute;n v&iacute;a remota a trav&eacute;s de la liga &uacute;nica <strong>https://conciliacion.centrolaboral.gob.mx/canal/</strong><strong class="mceNonEditable" data-nombre="solicitud_canal">[SOLICITUD_CANAL]</strong>&nbsp;ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>, bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong>.</p>
            <p style="text-align: justify; padding-left: 40px;">c) Que el presente convenio se celebra con la finalidad de dar por terminado el procedimiento de conciliaci&oacute;n prejudicial, seguido ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal <strong class="mceNonEditable" data-nombre="centro_nombre">[CENTRO_NOMBRE]</strong>, bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong> al tenor de las siguientes:&nbsp;</p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong> </span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">a) Las <strong>PARTES</strong> declaran que el presente convenio se celebra con la finalidad de dar por terminado el procedimiento de conciliaci&oacute;n prejudicial, seguido ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal de <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong>, bajo el n&uacute;mero de identificaci&oacute;n &uacute;nico <strong class="mceNonEditable" data-nombre="expediente_folio">[EXPEDIENTE_FOLIO]</strong>.</span></p>
            <p style="text-align: justify; padding-left: 40px;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">b) Que el d&iacute;a <strong class="mceNonEditable" data-nombre="fecha_actual">[FECHA_ACTUAL]</strong>, se celebr&oacute; la audiencia de conciliaci&oacute;n y, que, por as&iacute; convenir a sus intereses, la parte <strong>TRABAJADORA</strong> y la parte <strong>EMPLEADORA</strong> han llegado a un acuerdo para dirimir el conflicto suscitado, al tenor de las siguientes.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong></span></p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>C L &Aacute; U S U L A S:</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>PRIMERA</strong>. Las <strong>PARTES</strong>&nbsp;han determinado por as&iacute; convenir a sus intereses, la reinstalaci&oacute;n de la <strong>TRABAJADORA</strong>, conforme a lo estipulado por el art&iacute;culo 53, fracci&oacute;n I, de la Ley Federal del Trabajo.&nbsp;</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>SEGUNDA</strong>. La parte <strong>TRABAJADORA</strong> manifiesta bajo protesta de decir verdad, que el v&iacute;nculo laboral lo mantuvo exclusivamente con la parte <strong>EMPLEADORA</strong>. Por lo anterior, expresa que no existi&oacute; relaci&oacute;n laboral alguna con otras personas, incluido el personal que fung&iacute;a como superior jer&aacute;rquico en el centro de trabajo donde la parte <strong>TRABAJADORA</strong> desempe&ntilde;aba sus labores.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>TERCERA</strong>. La parte <strong>EMPLEADORA</strong> reinstala de manera inmediata a la parte <strong>TRABAJADORA</strong> y otorga en favor de la parte <strong>TRABAJADORA</strong> el pago acordado conforme a las disposiciones de la Ley Federal del Trabajo. Asimismo, la parte&nbsp; <strong>TRABAJADORA</strong> manifiesta su entera conformidad y aceptaci&oacute;n de la reinstalaci&oacute;n y el pago estipulado en la cl&aacute;usula <strong>CUARTA, </strong>&nbsp;as&iacute; como la forma en que se obtuvieron los conceptos que se describen en dicha cl&aacute;usula.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>CUARTA</strong>. La parte <strong>TRABAJADORA</strong> recibir&aacute; por parte de la parte <strong>EMPLEADORA</strong> la cantidad de <strong>$<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones">[RESOLUCION_TOTAL_PERCEPCIONES]</strong>&nbsp; </strong>(<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones_letra">[RESOLUCION_TOTAL_PERCEPCIONES_LETRA]</strong> pesos 00/100 moneda nacional), que incluye d&iacute;as de salarios ca&iacute;dos, considerando como salario mensual &nbsp; &nbsp;</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>QUINTA.</strong> <strong class="mceNonEditable" data-nombre="">[SI_RESOLUCION_PAGO_DIFERIDO]</strong>La parte <strong>EMPLEADORA</strong> manifiesta que pagar&aacute; en <strong class="mceNonEditable" data-nombre="resolucion_total_diferidos">[RESOLUCION_TOTAL_DIFERIDOS]</strong> exhibiciones, hasta culminar la cantidad de $<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones">[RESOLUCION_TOTAL_PERCEPCIONES]</strong> (<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones_letra">[RESOLUCION_TOTAL_PERCEPCIONES_LETRA]</strong> moneda nacional), tal como se muestra:</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="resolucion_pagos_diferidos">[RESOLUCION_PAGOS_DIFERIDOS]</strong>&nbsp; </span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"> <strong class="mceNonEditable" data-nombre="">[SI_RESOLUCION_PAGO_NO_DIFERIDO]</strong>La parte <strong>EMPLEADORA</strong> manifiesta que en este acto en fecha <strong class="mceNonEditable" data-nombre="fecha_actual">[FECHA_ACTUAL]</strong> pagar&aacute; a la parte&nbsp; <strong>TRABAJADORA</strong> en <strong>una sola exhibici&oacute;n</strong> la cantidad de $<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones">[RESOLUCION_TOTAL_PERCEPCIONES]</strong> (<strong class="mceNonEditable" data-nombre="resolucion_total_percepciones_letra">[RESOLUCION_TOTAL_PERCEPCIONES_LETRA]</strong> moneda nacional), el<strong> <strong class="mceNonEditable" data-nombre="audiencia_fecha_audiencia">[AUDIENCIA_FECHA_AUDIENCIA]</strong></strong>, en el domicilio que ocupa el Centro Federal de Conciliaci&oacute;n y Registro Laboral, Oficina Estatal de <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong>, con lo que se certifica el cumplimiento de su obligaci&oacute;n bajo el presente convenio, de conformidad con lo establecido en el art&iacute;culo 684-E, fracci&oacute;n XIV, de la Ley Federal del Trabajo.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt; letter-spacing: 0px;">En caso de que la parte&nbsp;</span><span style="font-size: 12pt; letter-spacing: 0px; font-weight: bolder;">EMPLEADORA</span><span style="font-size: 12pt; letter-spacing: 0px;">&nbsp;no cubra el pago de la cantidad estipulada y dentro del plazo determinado en esta cl&aacute;usula, deber&aacute; pagar a la parte&nbsp;</span><span style="font-size: 12pt; letter-spacing: 0px; font-weight: bolder;">TRABAJADORA</span><span style="font-size: 12pt; letter-spacing: 0px;">&nbsp;el equivalente a un d&iacute;a de salario diario, el cual se fijar&aacute; en raz&oacute;n del salario que percib&iacute;a dicha parte antes de finalizar la relaci&oacute;n de trabajo. Esa cantidad se sumar&aacute; a la previamente pactada, por cada d&iacute;a que transcurra, sin que se d&eacute; cabal cumplimiento al convenio, con fundamento en el art&iacute;culo 684-E, fracci&oacute;n XIV, &uacute;ltimo p&aacute;rrafo, de la Ley Federal del Trabajo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="">[FIN_SI_RESOLUCION_PAGO]</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>SEXTA</strong>. Las <strong>PARTES</strong> solicitan se apruebe y sancione este convenio, toda vez que se elabor&oacute; conforme a las disposiciones aplicables de la Ley Federal del Trabajo como resultado del di&aacute;logo de la conciliaci&oacute;n entre la parte <strong>TRABAJADORA</strong> y la parte <strong>EMPLEADORA</strong>. Asimismo, manifiestan que se encuentran conformes con el presente acuerdo por no contener cl&aacute;usula contraria a la costumbre, a la moral, ni renuncia a los derechos de las <strong>PARTES</strong>.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>S&Eacute;PTIMA</strong>. Las<strong> PARTES</strong>&nbsp;manifiestan que es su es su voluntad ratificar el presente convenio en todas y cada una de sus partes y la aprobaci&oacute;n de su contenido, por lo que no se reservan acci&oacute;n legal o derecho alguno para ejercitar con posterioridad a la firma del presente convenio.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>OCTAVA</strong>. Las<strong> PARTES</strong> solicitan ante el Centro Federal de Conciliaci&oacute;n y Registro Laboral que les sean expedidas las copias autorizadas del convenio, y en caso de pagos diferidos, que en el momento que se haya cumplido totalmente, se les expida acta en la que conste el cumplimiento de &eacute;ste, en t&eacute;rminos del art&iacute;culo 684-E, fracci&oacute;n XIV, primer p&aacute;rrafo, de la Ley Federal del Trabajo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>NOVENA.</strong> Las<strong> PARTES</strong>&nbsp;manifiestan que, en la celebraci&oacute;n del presente convenio, no existi&oacute; violencia, mala fe, dolo, lesi&oacute;n o cualquier otro tipo de vicio del consentimiento que pudiera nulificarlo.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>D&Eacute;CIMA.</strong> En caso de que no se cumpla los t&eacute;rminos de lo convenido en el presente instrumento, las <strong>PARTES</strong>&nbsp;deber&aacute;n acudir a los Tribunales Laborales a efecto de que se realice el procedimiento de ejecuci&oacute;n que la Ley Federal del Trabajo contempla.</span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">Enteradas las <strong>PARTES</strong>&nbsp;del alcance legal del presente convenio que se eleva a cosa juzgada, conforme al art&iacute;culo 684-E fracci&oacute;n XIII, mismo que se firma en <strong class="mceNonEditable" data-nombre="centro_domicilio_estado">[CENTRO_DOMICILIO_ESTADO]</strong><strong> en fecha <strong class="mceNonEditable" data-nombre="fecha_actual">[FECHA_ACTUAL]</strong></strong>, ante la fe de <strong class="mceNonEditable" data-nombre="conciliador_nombre_completo">[CONCILIADOR_NOMBRE_COMPLETO]</strong><strong>,</strong>&nbsp;funcionario conciliador, quien lo sanciona en este mismo acto. <strong>Doy fe.</strong></span></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_VIRTUAL]</strong></strong></span></p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="solicitud_firmas_partes_qr">[SOLICITUD_FIRMAS_PARTES_QR]</strong>&nbsp;</strong></span></p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong><strong class="mceNonEditable" data-nombre="conciliador_qr_firma">[CONCILIADOR_QR_FIRMA]</strong>&nbsp; <br />_______________________________<br /><strong class="mceNonEditable" data-nombre="conciliador_nombre_completo">[CONCILIADOR_NOMBRE_COMPLETO]</strong>&nbsp; <br />FUNCIONARIO CONCILIADOR</strong></span></p>
            <p style="text-align: justify;"><strong>Los c&oacute;digos QR asociadas a cada una de las partes no representan una forma de manifestaci&oacute;n de la voluntad, sin embargo, se convierten en firma electr&oacute;nica en caso de que la parte firmante utilice su firma electr&oacute;nica avanzada para manifestar su voluntad. Para que se puedan utilizar los c&oacute;digos QR ser&aacute; necesario que todas las partes firmantes cuenten con la firma electr&oacute;nica avanzada de lo contrario deber&aacute;n acudir a la Oficina Estatal del CFCRL para firmar el documento de manera aut&oacute;grafa.</strong></p>
            <p style="text-align: justify;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong> <strong class="mceNonEditable" data-nombre="">[SI_SOLICITUD_NO_VIRTUAL]</strong></strong></span></p>
            <table style="border-collapse: collapse; width: 100%;" border="0">
            <tbody>
            <tr>
            <td style="width: 50%; text-align: center;">
            <p>&nbsp;</p>
            <p><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">_________________________ &nbsp; &nbsp;</span></p>
            <p><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong class="mceNonEditable" data-nombre="solicitante_nombre_completo">[SOLICITANTE_NOMBRE_COMPLETO]</strong><br /></span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>LA PARTE EMPLEADORA&nbsp;</strong></span></p>
            </td>
            <td style="width: 50%;">
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;"><span style="font-family: Montserrat, sans-serif; font-size: 12pt;">&nbsp;________________________</span></p>
            <p style="text-align: center;"><span style="font-size: 12pt;"><strong class="mceNonEditable" data-nombre="solicitado_nombre_completo">[SOLICITADO_NOMBRE_COMPLETO]</strong>&nbsp; <br /></span><span style="font-family: Montserrat, sans-serif; font-size: 12pt;"><strong>LA PARTE TRABAJADORA</strong></span></p>
            </td>
            </tr>
            </tbody>
            </table>
            <p style="text-align: left;"><strong class="mceNonEditable" data-nombre="">[FIN_SI_SOLICITUD_VIRTUAL]</strong></p>
            <p>&nbsp;</p>
            <p style="text-align: justify;">&nbsp;</p>
            ',
            'plantilla_footer' => $plantillaOrigen->plantilla_footer,
            'tipo_documento_id' => 3
            ]
        );
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('plantilla_documentos', function (Blueprint $table) {
            //
        });
    }
}
